export { default as heart } from './heart.vue';
export { default as imdb } from './imdb.vue';
export { default as tv } from './tv.vue';
export { default as search } from './search.vue';
export { default as tomato } from './tomato.vue';
export { default as facebook } from './facebook.vue';
export { default as instagram } from './instagram.vue';
export { default as youtube } from './youtube.vue';
export { default as twitter } from './twitter.vue';
